---

- name: Copy logstash.yml.j2 to target server
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml

- name: Restart Logstash service
  service:
    name: logstash
    state: restarted
