---

- name: Copy kibana.yml.j2 to target server
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml

- name: Copy node.options.j2 to target server
  template:
    src: node.options.j2
    dest: /etc/kibana/node.options