---

- name: Copy kibana.yml.j2 to target server
  template:
    src: logstash_sample.conf.j2
    dest: /etc/logstash/conf.d/logstash_sample.conf

- name: Kopiere Template-Dateien
  template:
    src: "{{ item }}"
    dest: "{{ logstash_config_path }}/conf.d"
  with_fileglob:
    - templates/*.j2