---

- name: Copy Template Files without .j2 extension
  template:
    src: "{{ item }}"
    dest: "{{ path_config }}/conf.d/{{ item | regex_replace('.j2$', '') }}"
  loop: "{{ main_pipeline }}" # main pipeline files unter vars/main.yml definieren

