---

# - name: Copy Template Files without .j2 extension
#   template:
#     src: "{{ item }}"
#     dest: "{{logstash_config_path}}/conf.d/{{ item | regex_replace('.j2$', '') }}"
#   loop: "{{ logstash_main_pipeline }}"



- name: Copy Template Files without .j2 extension
  template:
    src: "{{ item }}"
    dest: "{{logstash_config_path}}/conf.d/{{ item | regex_replace('.j2$', '') }}"
  with_fileglob:
    - "./roles/pipeline/templates/*.j2"
