---

# - name: Copy Template Files without .j2 extension
#   template:
#     src: "{{ item }}"
#     dest: "{{logstash_config_path}}/conf.d/{{ item | regex_replace('.j2$', '') }}"
#   loop: "{{ logstash_main_pipeline }}"



    - name: Copy Jinja2 templates to destination
      template:
        src: "{{ item }}"
        dest: "{{logstash_config_path}}/conf.d/{{{ item | basename }}"
      loop: "{{ lookup('fileglob', '*.j2') }}"

