---

- name: Copy elasticsearch.yml.j2 to target server
  template:
    src: "elasticsearch.yml.j2"
    dest: "{{ elasticsearch_config_path }}/elasticsearch.yml"

- name: Copy log4j2.properties to target server
  template:
    src: "log4j2.properties.j2"
    dest: "{{ elasticsearch_config_path }}/log4j2.properties"

- name: Copy jvm.options to target server
  template:
    src: "jvm.options.j2"
    dest: "{{ elasticsearch_config_path }}/jvm.options"


