---
- name: Deploy Logstash Configuration
  hosts: elasticsearch_server
  become: yes

  roles:
    - elasticsearch

  tasks:
  - name: Stoppe Elasticsearch-Dienst
    systemd:
      name: elasticsearch
      state: stopped

  - name: Starte Elasticsearch-Dienst
    systemd:
      name: elasticsearch
      state: started