---
- name: Deploy Filebeat Configuration
  hosts: filebeat
  become: yes

  roles:
    - filebeat

  tasks:
  - name: Stoppe Filebeat-Dienst
    systemd:
      name: filebeat
      state: stopped

  - name: Starte Filebeat-Dienst
    systemd:
      name: filebeat
      state: started