---
- name: Deploy Logstash Configuration
  hosts: logstash_server
  become: yes

  roles:
    - logstash

  tasks:
  - name: Stoppe Logstash-Dienst
    systemd:
      name: logstash
      state: stopped

  - name: Starte Logstash-Dienst
    systemd:
      name: logstash
      state: started